// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-sf6P0Br5Udsd8f8nOJPmYtaMt_stZF4',
    appId: '1:708018380779:web:48b420715d831ff1e203ae',
    messagingSenderId: '708018380779',
    projectId: 'localnotification-cc760',
    authDomain: 'localnotification-cc760.firebaseapp.com',
    storageBucket: 'localnotification-cc760.firebasestorage.app',
    measurementId: 'G-QX3GNPT317',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbHR4lVzRabf0Dxkumka6YoshU4CrQ4Bs',
    appId: '1:708018380779:android:2c2b7d714656ca8be203ae',
    messagingSenderId: '708018380779',
    projectId: 'localnotification-cc760',
    storageBucket: 'localnotification-cc760.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApkd1yGa3hNZZImeSlHhWxl-EJOAU6-0U',
    appId: '1:708018380779:ios:61b980fd637350c9e203ae',
    messagingSenderId: '708018380779',
    projectId: 'localnotification-cc760',
    storageBucket: 'localnotification-cc760.firebasestorage.app',
    iosBundleId: 'com.example.notificationLocalApp',
  );
}
